package com.jm.codergifs.model;

import javax.persistence.*;

@Entity
@Table(name="categories")
public class Category {

    @Id // Sets the Id as the Primary Key
    // Allows the Id to be generated by the underlying database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    private String name;

    public Category() {
        // non-argument constructor needed for the JPA
    }

    public long getId() {
        return id;
    }

    public Category(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
